select
    observation_id,
    device_id,
    trim(host_manufacturer) as host_manufacturer,
    trim(host_model) as host_model,
    architecture,
    os_family,
    os_version,
    os_build,
    connection_path_json,
    connection_signature,
    driver_name,
    driver_version,
    firmware_version,
    software_name,
    software_version,
    outcome,
    conditions_json,
    evidence_source_type,
    source_url,
    source_title,
    cast(observed_at as timestamp) as observed_at,
    cast(recorded_at as timestamp) as recorded_at,
    limitations_json,
    notes,
    record_sha256
from {{ source('bronze', 'compatibility_observations') }}
