select
    statement_id,
    device_id,
    architecture,
    os_family,
    version_mode,
    versions_json,
    minimum_version,
    connection_kind,
    minimum_usb_generation,
    driver_name,
    driver_version,
    software_name,
    software_version,
    support_status,
    conditions_json,
    evidence_source_type,
    sources_json,
    source_note,
    cast(reviewed_at as timestamp) as reviewed_at,
    cast(recorded_at as timestamp) as recorded_at,
    limitations_json,
    record_sha256
from {{ source('bronze', 'support_statements') }}
