// Generated by scripts/generate-evidence-index.mjs. Do not edit by hand.
// Every canonical evidence JSON file must be represented here so the public web app cannot silently omit reviewed evidence.
import observation0 from "../../../../data/evidence/observations/avrdude-ft232r-windows11-arm64.json";
import supportStatement0 from "../../../../data/evidence/vendor/ftdi-ft232r-windows11-arm64.json";
import supportStatement1 from "../../../../data/evidence/vendor/saleae-logic-pro-8-macos-arm64.json";
import supportStatement2 from "../../../../data/evidence/vendor/saleae-logic-pro-8-macos-x64.json";
import supportStatement3 from "../../../../data/evidence/vendor/saleae-logic-pro-8-windows-arm64.json";
import supportStatement4 from "../../../../data/evidence/vendor/saleae-logic-pro-8-windows-x64.json";

export const canonicalObservationDocuments = [
  observation0,
] as const;

export const canonicalSupportStatementDocuments = [
  supportStatement0,
  supportStatement1,
  supportStatement2,
  supportStatement3,
  supportStatement4,
] as const;
